# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 06:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ControlMyRent', '0002_auto_20170420_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.AddField(
            model_name='imovel',
            name='UF',
            field=models.CharField(choices=[('AC', 'Masculino'), ('AL', 'Feminino'), ('AP', 'Masculino'), ('AM', 'Feminino'), ('BA', 'Masculino'), ('CE', 'Feminino'), ('DF', 'Masculino'), ('ES', 'Feminino'), ('GO', 'Masculino'), ('MA', 'Feminino'), ('MT', 'Masculino'), ('MS', 'Feminino'), ('MG', 'Masculino'), ('PA', 'Feminino'), ('PB', 'Masculino'), ('PR', 'Feminino'), ('PE', 'Feminino'), ('PI', 'Masculino'), ('RJ', 'Feminino'), ('RN', 'Masculino'), ('RS', 'Feminino'), ('RO', 'Masculino'), ('RR', 'Feminino'), ('SC', 'Feminino'), ('SP', 'Masculino'), ('SE', 'Feminino'), ('TO', 'Masculino')], default='ZZ', max_length=2),
        ),
        migrations.AddField(
            model_name='imovel',
            name='id_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'M'), ('Feminino', 'F')], max_length=1),
        ),
    ]
