# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlMyRent', '0002_userprofile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
