# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ControlMyRent', '0003_auto_20170516_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagensImovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, upload_to='imovel_image', verbose_name='Imagem')),
                ('imovel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ControlMyRent.Imovel')),
            ],
        ),
    ]
