# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlMyRent', '0003_auto_20170422_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='id_User',
            new_name='Imovel_User',
        ),
    ]
