# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlMyRent', '0004_auto_20170422_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='Imovel_User',
            new_name='User',
        ),
    ]
