# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlMyRent', '0005_auto_20170517_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='imovelPic',
        ),
        migrations.AddField(
            model_name='imovel',
            name='profilePic',
            field=models.ImageField(blank=True, upload_to='imovel_image'),
        ),
    ]
