# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlMyRent', '0005_auto_20170422_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
