# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ControlMyRent', '0006_auto_20170422_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imovel',
            old_name='CEP',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='imovel',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='imovel',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='imovel',
            old_name='UF',
            new_name='uf',
        ),
        migrations.RenameField(
            model_name='imovel',
            old_name='User',
            new_name='user',
        ),
    ]
