# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 09:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ControlMyRent', '0007_auto_20170422_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='nome',
            field=models.CharField(default=10, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imovel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
