# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlMyRent', '0008_auto_20170517_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='stats',
            field=models.CharField(choices=[('Alugar', 'Alugar'), ('Vender', 'Vender')], max_length=7),
        ),
    ]
