# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 02:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ControlMyRent', '0009_auto_20170422_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imovel', to=settings.AUTH_USER_MODEL),
        ),
    ]
