# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlMyRent', '0010_auto_20170425_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='stats',
            field=models.CharField(choices=[('Alugar', 'Alugar'), ('Alugado', 'Alugado'), ('Vender', 'Vender'), ('Vendido', 'Vendido')], default='NO', max_length=7),
        ),
    ]
